stockservice:
  url: http://localhost:8901

server:
  port: 8900

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      stockService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 1
        automatic-transition-from-open-to-half-open-enabled: true
